Remove cutenode/action-always-fail action
Replaced with native workflow command.

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -150,7 +150,9 @@ jobs:
 
     - name: Missing Dependency Cache
       if: inputs.deps_cache_key && steps.deps-cache.outputs.cache-hit != 'true'
-      uses: cutenode/action-always-fail@v1
+      run: |
+        echo "::error::Missing dependency cache for given deps_cache_key input."
+        exit 1
 
     - name: Setup Dependency Environment
       if: steps.deps-cache.outputs.cache-hit == 'true'
